---
- name: Converge
  hosts: all
  gather_facts: false
  vars:
    certs_source_base: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/molecule/shared/certs"
  tasks:

    # # Default - no configuration provided
    # - saiello.kafka.kafka_config:
    # - debug: var=__kafka_config

    # Configuration #1 - xxxxx
    - saiello.kafka.kafka_config:
        config:
          advertise_host: "{{ ansible_host }}"

          tls:
            trustedCAs:
              - "{{ certs_source_base }}/ca-root.pem"
          listeners:
            - name: replication
              port: 9091
              tls: true
            - name: admin
              port: 9093
              tls: true
            - name: authenticated
              port: 9094
              tls: true

    - debug: var=__kafka_config
