---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: instance
provisioner:
  name: ansible
  ansible_args:
    - -vvv
  # config_options:
  #   defaults:
  #     stdout_callback: yaml
  #     stderr_callback: yaml
