---
- name:  Check role parameters
  block:
    - name: "Kafka Zookeeper mode"
      ansible.builtin.assert:
        that:
          - kafka_broker_id is defined
        quiet: true
      when:
        - not kafka_kraft_mode

    - name: "Kafka KRaft mode"
      ansible.builtin.assert:
        that:
          - ((kafka_node_id is defined) or (kafka_broker_id is defined) or (kafka_controller_id is defined))
          - kafka_cluster_id is defined
        quiet: true
      when:
        - kafka_kraft_mode

- name: Debug config
  ansible.builtin.debug:
    var: __kafka_input_config

- name: Build kafka config
  saiello.kafka.kafka_config:
    config: "{{ __kafka_input_config }}"

- name: Debug kafka config
  ansible.builtin.debug: var=__kafka_config

- name: Debug Admin Kafka config
  ansible.builtin.debug: var=__admin_config

- name: Check kafka_inter_broker_listener_name is valid
  ansible.builtin.assert:
    that:
      - kafka_inter_broker_listener_name is defined
      - kafka_inter_broker_listener_name in __kafka_config.listeners
    msg: |
      kafka_inter_broker_listener_name is undefined or not valid. 
      Allowed values are: {{ __kafka_config.listeners.values() }}
    quiet: true
  when: (not kafka_kraft_mode) or 
        (kafka_kraft_mode and kafka_kraft_role == 'broker')

- name: Initialize kafka_java_opts
  ansible.builtin.set_fact:
    _kafka_java_opts: "{{ kafka_java_opts | default([]) }}"

- name: Find JMX prometheus javaagent file
  ansible.builtin.find:
    paths: "{{ kafka_home }}/libs"
    file_type: file
    patterns: "^jmx_prometheus_javaagent-.*.jar$"
    use_regex: true
  register: jmx_prometheus_javaagent_file_result
  when:
    - kafka_metrics_enabled
    - kafka_metrics_agent_file is not defined
  run_once: true
  become: true

- name: Set the javaagent jmx_prometheus_javaagent
  ansible.builtin.set_fact:
    _kafka_java_opts: "{{ _kafka_java_opts + [ '-javaagent:' + _kafka_metrics_agent_file + '=' + (kafka_metrics_port | string) + ':' + kafka_metrics_config_file ] }}"
  vars:
    _discovered_kafka_metrics_agent_file: "{{ jmx_prometheus_javaagent_file_result.files | default([]) | map(attribute='path') | first | default('') }}"
    _kafka_metrics_agent_file: "{{ kafka_metrics_agent_file | default(_discovered_kafka_metrics_agent_file) }}"
  when:
    - kafka_metrics_enabled
    - _kafka_metrics_agent_file | length > 0

- name: Return Kafka microversion
  ansible.builtin.command: "{{ kafka_home }}/bin/kafka-topics.sh --version"
  register: __kafka_microversion
  changed_when: false
  become: true

- name: Set kafka_microversion_is_v4
  ansible.builtin.set_fact:
    kafka_microversion_is_v4: "{{ (__kafka_microversion.stdout | regex_replace('\\.redhat-.*$', '')) is version('3.9.2', '>') }}"
  when: not ansible_check_mode
