---
- name: Stop Kafka
  ansible.builtin.service:
    name: "{{ kafka_service_name }}"
    state: stopped
  become: true

- name: Ensure Kafka is stopped
  ansible.builtin.shell: jcmd | grep -w "kafka.Kafka" | grep "server.properties"
  register: kafka_check
  changed_when: false
  failed_when: kafka_check.rc == 0
  when: not kafka_kraft_mode

- name: Ensure Kafka Controller is stopped
  ansible.builtin.shell: jcmd | grep -w "kafka.Kafka" | grep "controller.properties"
  register: kafka_check
  changed_when: false
  failed_when: kafka_check.rc == 0
  when:
    - kafka_kraft_mode
    - kafka_kraft_role == 'controller'

- name: Ensure Kafka Broker is stopped
  ansible.builtin.shell: jcmd | grep -w "kafka.Kafka" | grep "broker.properties"
  register: kafka_check
  changed_when: false
  failed_when: kafka_check.rc == 0
  when:
    - kafka_kraft_mode
    - kafka_kraft_role == 'broker'