---
- name: Start Kafka Service
  ansible.builtin.service:
    name: "{{ kafka_service_name }}"
    state: started
  notify: Restart kafka

- name: Check Kafka Service
  ansible.builtin.include_tasks: service_check.yml
