---
- name: Gather KRaft facts
  ansible.builtin.setup:
  delegate_to: "{{ item }}"
  delegate_facts: true
  with_items: "{{ groups[kafka_controller_servers_ansible_group] }}"

- name: Init KRaft controller facts
  ansible.builtin.set_fact:
    controller_quorum_bootstrap_servers: []

- name: Assert existence of controller listener '{{ kafka_controller_listener_name }}'
  ansible.builtin.assert:
    that:
      - kafka_listeners is defined
      - (kafka_listeners | selectattr('name', 'defined') | selectattr('name', 'eq', kafka_controller_listener_name) | list | length) > 0
    fail_msg: "ERROR: Listener '{{ kafka_controller_listener_name }}' is missing from 'kafka_listeners' list."
    success_msg: "Listener '{{ kafka_controller_listener_name }}' successfully validated."

- name: Set kafka_controller_listener_port fact
  ansible.builtin.set_fact:
    kafka_controller_listener_port: "{{ (kafka_listeners | selectattr('name', 'eq', kafka_controller_listener_name) | map(attribute='port') | first) }}"

- name: Set KRaft controller quorum facts
  ansible.builtin.set_fact:
    controller_quorum_bootstrap_servers: "{{ controller_quorum_bootstrap_servers + [ (hostvars[item]['_controller_kafka_advertised_host'] | default(hostvars[item]['kafka_advertised_host'])) + ':' + (kafka_controller_listener_port | string) ] }}"
  with_items: "{{ groups[kafka_controller_servers_ansible_group] }}"
  run_once: true

- name: Debug KRaft controller quorum
  ansible.builtin.debug:
    var: controller_quorum_bootstrap_servers
