  
  
  - name: Copy truststore jks file
    copy:
      src: "{{ kafka_ssl_truststore_file }}"
      dest: "{{ kafka_ssl_truststore_location }}"
    with_items: 

  - name: Copy keystore jks file
    copy:
      src: "{{ kafka_ssl_keystore_file }}"
      dest: "{{ kafka_ssl_keystore_location }}"