---
kafka_connect_user: kafka
kafka_connect_group: kafka

kafka_connect_properties_file: "{{ kafka_home }}/config/connect-distributed.properties"
kafka_connect_template_backup: true

# Systemd unit config
kafka_connect_service_name: kafka-connect
kafka_connect_service_file: /usr/lib/systemd/system/{{ kafka_connect_service_name }}.service
kafka_connect_service_environment_file: /etc/sysconfig/{{ kafka_connect_service_name }}
kafka_connect_service_after: 
  - network-online.target
kafka_connect_service_timeout_stop_sec: 300
kafka_connect_service_standard_output: journal

# JVM Memory config
kafka_connect_max_heap: 1G
kafka_connect_min_heap: 1G

# Logging
kafka_connect_log4j_dir: /var/log/kafka-connect

# Unique cluster name
kafka_connect_group_id: connect-cluster

# Serialize/Deserialize config
kafka_connect_key_converter: org.apache.kafka.connect.json.JsonConverter
kafka_connect_value_converter: org.apache.kafka.connect.json.JsonConverter

kafka_connect_key_converter_schemas_enable: true
kafka_connect_value_converter_schemas_enable: true

# Internal topics config
kafka_connect_offset_storage_topic: connect-offsets
kafka_connect_offset_storage_replication_factor: 1
kafka_connect_config_storage_topic: connect-configs
kafka_connect_config_storage_replication_factor: 1
kafka_connect_status_storage_topic: connect-status
kafka_connect_status_storage_replication_factor: 1


# Offset flush interval
kafka_connect_offset_flush_int_ms: 10000

kafka_connect_jmx_enabled: false
kafka_connect_jmx_management_port: 9990

kafka_connect_bootstrap_servers: localhost:9092

kafka_connect_listeners:
  - HTTP://:8083

kafka_connect_connectors: []

kafka_connect_skip_verify_listening: false

# move tos fact
_kafka_connect_java_opts: []
# kafka_connect_connectors:
#   - name: source
#     config:
#       connector.class: "org.apache.kafka.connect.mirror.MirrorSourceConnector"
#       tasks.max: "10"

#       source.cluster.alias: "cluster-1"
#       target.cluster.alias: "cluster-2"
#       source.cluster.bootstrap.servers: "broker-c1-1:9092,broker-c1-2:9092"
#       target.cluster.bootstrap.servers: "broker-c2-1:9092,broker-c2-2:9092"

#       topics: "topic-a,topic-b"
#       replication.policy.class: "org.apache.kafka.connect.mirror.IdentityReplicationPolicy"
#       replication.factor: "3"
#   - name: checkpoint
#     config:
#       connector.class: "org.apache.kafka.connect.mirror.MirrorCheckpointConnector"
#       tasks.max: "10"

#       source.cluster.alias: "cluster-1"
#       target.cluster.alias: "cluster-2"
#       source.cluster.bootstrap.servers: "broker-c1-1:9092,broker-c1-2:9092"
#       target.cluster.bootstrap.servers: "broker-c2-1:9092,broker-c2-2:9092"

#       groups: "group-1,group-2"

#       replication.policy.class: "org.apache.kafka.connect.mirror.IdentityReplicationPolicy"
#       checkpoints.topic.replication.factor: "3"