- name: Configure Kafka Controller
  include_role:
    name: saiello.kafka.kafka_systemd_broker
    tasks_from: "{{ tasks_from | default('main.yml') }}"
  vars:
    kafka_advertised_interface_name: "{{ _controller_kafka_advertised_interface_name }}"
    kafka_advertised_host: "{{ _controller_kafka_advertised_host }}"
    kafka_inter_broker_listener_name: "{{ _controller_kafka_inter_broker_listener_name }}"
    kafka_kerberos_keytab_location: "{{ _controller_kafka_kerberos_keytab_location }}"
    kafka_kerberos_keytab_skip_copy: "{{ _controller_kafka_kerberos_keytab_skip_copy }}"
    kafka_kerberos_keytab_file: "{{ _controller_kafka_kerberos_keytab_file }}"
    kafka_kerberos_principal: "{{ _controller_kafka_kerberos_principal }}"
    kafka_java_opts: "{{ _controller_kafka_java_opts }}"
    kafka_max_heap: "{{ _controller_kafka_max_heap }}"
    kafka_min_heap: "{{ _controller_kafka_min_heap }}"
    kafka_skip_verify_listening: "{{ _controller_kafka_skip_verify_listening }}"
    kafka_skip_verify_under_replicated_partitions: "{{ _controller_kafka_skip_verify_under_replicated_partitions }}"
    kafka_skip_verify_unavailable_partitions: "{{ _controller_kafka_skip_verify_unavailable_partitions }}"
    kafka_server_properties_template: "{{ _controller_kafka_server_properties_template }}"
    kafka_server_properties_file_name: "{{ _controller_kafka_server_properties_file_name }}"
    kafka_jaas_config_file_name: "{{ _controller_kafka_jaas_config_file_name }}"
    kafka_service_name: "{{ _controller_kafka_service_name }}"  
    kafka_service_after: "{{ _controller_kafka_service_after }}"
    kafka_metrics_enabled: "{{ _controller_kafka_metrics_enabled }}"
    kafka_metrics_port: "{{ _controller_kafka_metrics_port }}"
    kafka_log4j_dir: "{{ _controller_kafka_log4j_dir }}"
    kafka_log_dirs: "{{ _controller_kafka_log_dirs }}"
    kafka_admin: "{{ _controller_kafka_admin }}"
    kafka_service_limit_mem_lock: "{{ _controller_kafka_service_limit_mem_lock }}"
    kafka_service_standard_output: "{{ _controller_kafka_service_standard_output }}"
    
    kafka_listeners: "{{ _controller_kafka_listeners | default([]) }}"
    kafka_authorization: "{{ _controller_kafka_authorization | default(omit) }}"
    kafka_additional_conf: "{{ _controller_kafka_additional_conf | default({}) }}"
    
    kafka_kraft_mode: true
    kafka_kraft_role: controller
