---
# skip prerun because I am experiencing the issue described here:
# https://github.com/ansible/ansible-lint/issues/2070
prerun: false
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: registry.access.redhat.com/ubi8/ubi-init:latest
    pre_build_image: true
    privileged: true
    command: "/usr/sbin/init"
    port_bindings:
      - 9092:9092
    published_ports:
      - 0.0.0.0:9092:9092/TCP
    groups:
      - kafka
      - zookeeper

provisioner:
  name: ansible
  ansible_args:
    - --diff
  playbooks:
    converge: converge.yml
    prepare: ../shared/prepare.yml
    verify: verify.yml
  inventory:
    group_vars:
      all:

    host_vars:
      instance:
        kafka_home: /opt/kafka/kafka_2.13-3.1.1

        zookeeper_myid: 0
        zookeeper_interface_name: eth0

        kafka_broker_id: 0
        kafka_advertised_interface_name: eth0
        # kafka_server_properties_template: ${MOLECULE_SCENARIO_DIRECTORY}/custom-server.properties.j2
        kafka_additional_conf:
          auto.create.topics.enable: 'false'
      localhost:
        ansible_python_interpreter: "{{ ansible_playbook_python }}"
verifier:
  name: ansible
