---
- name: Prepare
  hosts: all
  tasks:

    - name: "Ensure required packages are installed."
      ansible.builtin.yum:
        name:
          - sudo
          - java-1.8.0-openjdk
        state: present

    - name: Display Ansible version
      ansible.builtin.debug:
        msg: "Ansible version is  {{ ansible_version.full }}"
