---
__kafka_commands_bin: "{{ kafka_home }}/bin"

__kafka_input_config:
  advertised_host: "{{ kafka_advertised_host }}"
  tls: "{{ kafka_tls_config | default({}) }}"
  authorization: "{{ kafka_authorization | default({}) }}"
  listeners: "{{ kafka_listeners }}"
  additional_config: "{{ kafka_additional_conf }}"
  admin: "{{ kafka_admin }}"
  kraft_mode: "{{ kafka_kraft_mode }}"
  kraft_controller_listener_name: "{{ kafka_controller_listener_name }}"
  kraft_roles: "{{ group_names }}"

__kafka_admin_config: "{{ kafka_home }}/config/admin.properties"
__kafka_storage_config: "{{ kafka_home }}/config/kraft/{{ kafka_server_properties_file_name }}"

__kafka_bootstrap_servers: --bootstrap-server {{ __admin_config.listener }}
__kafka_commands_opts: "{{ __admin_config.require_command_config | ternary('--command-config ' + __kafka_admin_config, '') }}"
__kafka_commands_topics: "{{ __kafka_commands_bin }}/kafka-topics.sh {{ __kafka_bootstrap_servers }} {{ __kafka_commands_opts }}"

__kafka_commands_storage: "{{ __kafka_commands_bin }}/kafka-storage.sh"
__kafka_storage_info_opts: "info --config {{ __kafka_storage_config }}"
__kafka_storage_format_opts: "format --config {{ __kafka_storage_config }} --cluster-id {{ kafka_cluster_id }} --ignore-formatted"