---
__kafka_commands_bin: "{{ kafka_home }}/bin"

__kafka_admin_port: "{{ (kafka_listeners | items2dict(key_name='name', value_name='port'))[kafka_admin_listener_name] | int }}"
__kafka_bootstra_servers: --bootstrap-server {{ kafka_advertised_host }}:{{ __kafka_admin_port }}

__kafka_commands_topics: "{{ __kafka_commands_bin }}/kafka-topics.sh {{ __kafka_bootstra_servers }}"
