---
- name: Verify cluster status
  import_playbook: ../../playbooks/verify.yml
  vars:
    kafka_skip_zookeeper_verify: true
    kafka_skip_verify_produce_consume_data: false
    kafka_verify_topic_replication_factor: 1
