---
- name: Restart zookeeper
  ansible.builtin.service:
    name: "{{ zookeeper_service_name }}"
    state: restarted
  become: true

- name: Check Zookeeper Service
  ansible.builtin.include_tasks: service_check.yml
