---
kafka_scala_version: "{{ kafka_versions[kafka_version]['scala_version'] }}"

# upstream
kafka_archive_filename: "kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz"
kafka_download_base_url: "https://archive.apache.org/dist/kafka"
kafka_download_url: "{{ kafka_download_base_url }}/{{ kafka_version }}/{{ kafka_archive_filename }}"
kafka_dirname: "kafka_{{ kafka_scala_version }}-{{ kafka_versions[kafka_version]['upstream']['version'] | regex_replace(' \\((.*)\\)$', '') }}"

# amqstreams
amqstreams_archive_filename: "amq-streams-{{ kafka_versions[kafka_version]['amqstreams']['product_version'] }}-bin.zip"
amqstreams_download_base_url: "https://access.redhat.com/jbossnetwork/restricted/softwareDownload.html"
amqstreams_download_url: "{{ amqstreams_download_base_url }}?softwareId={{ kafka_versions[kafka_version]['amqstreams']['rhn_id'] }}"
amqstreams_dirname: "kafka_{{ kafka_scala_version }}-{{ kafka_versions[kafka_version]['amqstreams']['version'] | regex_replace(' \\((.*)\\)$', '') }}"

kafka_versions:
  3.2.3:
    scala_version: 2.13
    upstream:
      version: 3.2.3 (Commit:50029d3ed8ba576f)
    amqstreams:
      version: 3.2.3.redhat-00003 (Commit:8c8f89d8e34196ab)
      product_version: 2.2.0
      rhn_id: 104745
  3.1.0:
    scala_version: 2.13
    upstream:
      version: 3.1.0 (Commit:37edeed0777bacb3)
    amqstreams:
      version: 3.1.0.redhat-00004 (Commit:4c168d2882c7f93d)
      product_version: 2.1.0
      rhn_id: 104335
  3.0.0:
    scala_version: 2.13
    upstream:
      version: 3.0.0 (Commit:8cb0a5e9d3441962)
    amqstreams:
      version: 3.0.0.redhat-00008 (Commit:a92f6b92b6cb42fe)
      product_version: 2.0.1
      rhn_id: 104108
  2.8.0:
    scala_version: 2.12
    upstream:
      version: 2.8.0 (Commit:ebb1d6e21cc92130)
    amqstreams:
      version: 2.8.0.redhat-00004 (Commit:e4403b1af4b1e4d5)
      product_version: 1.8.4
      rhn_id: 103708