---
# skip prerun because I am experiencing the issue described here:
# https://github.com/ansible/ansible-lint/issues/2070
prerun: false
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  ansible-lint -v
platforms:

  - name: machine1
    image: registry.access.redhat.com/ubi8/ubi-init:latest
    pre_build_image: true
    privileged: true
    command: "/usr/sbin/init"
    groups:
      - kafka
      - zookeeper
    networks:
      - name: molecule

  - name: machine2
    image: registry.access.redhat.com/ubi8/ubi-init:latest
    pre_build_image: true
    privileged: true
    command: "/usr/sbin/init"
    groups:
      - kafka
      - zookeeper
    networks:
      - name: molecule


  - name: machine3
    image: registry.access.redhat.com/ubi8/ubi-init:latest
    pre_build_image: true
    privileged: true
    command: "/usr/sbin/init"
    groups:
      - kafka
      - zookeeper
    networks:
      - name: molecule

provisioner:
  name: ansible
  ansible_args:
    - --diff
  playbooks:
    converge: converge.yml
    prepare: ../shared/prepare.yml
    verify: verify.yml
  inventory:
    group_vars:
      all:
        kafka_home: /opt/kafka/kafka_2.13-3.1.1
        kafka_advertised_interface_name: eth0
        zookeeper_interface_name: eth0
      
      kafka:
        kafka_advertised_host: "{{ ansible_hostname }}"

        kafka_authorization:
          type: simple
          deny_by_default: true
          super_users:
            - User:CN=kafka,O=Saiello,L=Rome,C=IT
            - User:CN=admin,O=Saiello,L=Rome,C=IT

        kafka_tls_config:
          enabled: true
          trustedCA: /etc/certs/ca-root.pem
          keystore:
            location: /etc/certs/cert-cluster.p12
            password: changeit
            type: PKCS12

        kafka_listeners:

          - name: replication
            port: 9091
            tls: true 
            authentication:
              type: tls
       
          - name: admin
            port: 9092
            tls: true
            authentication:
              type: tls

          - name: authenticated
            port: 9094
            tls: true 
            authentication:
              type: scram-sha-512

        kafka_additional_conf:
          num.partitions: 1
          log.retention.hours: 148

        kafka_inter_broker_listener_name: replication
        
        kafka_admin:
          listener_name: admin
          authentication:
            tls:
              trustedCA: /etc/certs/ca-root.pem
              keystore:
                location: /etc/certs/cert-cluster.p12
                password: changeit
                type: PKCS12

    host_vars:
      machine1:
        kafka_broker_id: 1
        zookeeper_myid: 1
      machine2:
        kafka_broker_id: 2
        zookeeper_myid: 2
      machine3:
        kafka_broker_id: 3
        zookeeper_myid: 3
      localhost:
        ansible_python_interpreter: "{{ ansible_playbook_python }}"
verifier:
  name: ansible
