---
# Red Hat Accounts fail due to SSO change: https://github.com/ansible-middleware/redhat-csp-download/issues/20
- name: Download from Red Hat Customer Portal
  collections:
  - middleware_automation.redhat_csp_download
  redhat_csp_download:
    dest: "{{ __kafka_local_archive_path }}"
    url: "{{ kafka_install_download_base_url }}"
    username: "{{ lookup('env', 'RHN_USERNAME', default = kafka_install_url_username) }}"
    password: "{{ lookup('env', 'RHN_PASSWORD', default = kafka_install_url_password) }}"
  delegate_to: localhost
  run_once: true