---
- name: Check Services
  hosts: all
  
  tasks:

    - name: "Ensure kafka_home exists"
      ansible.builtin.assert:
        that:
          - kafka_home is defined

    - name: Check Zookeeper Service
      ansible.builtin.include_role:
        name: kafka_systemd_zookeeper
        tasks_from: service_check.yml

    - name: Kafka prereqs
      ansible.builtin.include_role:
        name: kafka_systemd_broker
        tasks_from: prereqs.yml

    - name: Ensure Admin 
      ansible.builtin.include_role:
        name: kafka_systemd_broker
        tasks_from: setup_admin.yml

    - name: Check Kafka Service
      ansible.builtin.include_role:
        name: kafka_systemd_broker
        tasks_from: service_check.yml
