---

- name: Setup ZooKeeper Controller
  hosts: zookeeper
  tags: 
    - zookeeper
  roles:
    - saiello.kafka.kafka_install
    - saiello.kafka.kafka_systemd_zookeeper

- name: Setup Kafka Controller
  hosts: controller
  tags: 
    - controller
  roles:
    - saiello.kafka.kafka_install
    - role: saiello.kafka.kafka_systemd_controller
      when: kafka_kraft_role == 'controller'

- name: Setup Kafka Broker
  hosts: kafka,broker
  tags: 
    - kafka
    - broker
  roles:
    - saiello.kafka.kafka_install
    - role: saiello.kafka.kafka_systemd_broker
      when: kafka_kraft_role == 'broker'

- name: Setup Kafka Connect
  hosts: connect
  tags: 
    - connect
  roles:
    - saiello.kafka.kafka_install
    - saiello.kafka.kafka_systemd_connect
