---
- name: Update a cluster
  hosts: all
  serial: 1
  pre_tasks:
    - name: "Ensure kafka_home exists"
      ansible.builtin.assert:
        that:
          - kafka_home is defined
  roles:
    - { role: kafka_systemd_zookeeper, when: not kafka_kraft_mode }
    - kafka_systemd_broker